### ISSUE TITLE
Add Google Voice

### ISSUE THREAD

**Issue by KapeteinPannenkoek** [asolkar/ffx-addon-gglappbtn#18]
There does not appear to be support for the Google app **Voice** (voice.google.com). 

I use this app separately from Hangouts, and need a shortcut to it. And since some Google apps in the list are now defunct (Allo and Music), this seems like an easy add.

Thanks.

**Comment by asolkar** [comment]
Added Voice in a8206dffdc97b7848e9bda18fa4f19327977117f
Included in release 1.3 of the addon
