### ISSUE TITLE
Additional Apps

### ISSUE THREAD

**Issue by pirlet** [asolkar/ffx-addon-gglappbtn#6]
I love this option. Thank you for making it. Can you add Google Classroom? That would be huge!

**Comment by NovaViper** [comment]
Hey, I have an add-on you can look at while your updating, its called [
Shortcuts for Google™ Products](https://addons.mozilla.org/en-US/firefox/addon/google-shortcuts/). Just thought some inspiration for the next update was needed

**Comment by fanaugen** [comment]
I miss [Google Slides](https://slides.google.com)

**Comment by asolkar** [comment]
Added support with commit 420ee6f1ebddd1bbeae1fd8c40740244a7c18392

Will be in upcoming release
