### ISSUE TITLE
Not compatible with multiprocess

### ISSUE THREAD

**Issue by simonbcn** [asolkar/ffx-addon-gglappbtn#8]
Firefox 50

It isn't marked like compatible compatible with multiprocess. See: https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/ and https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible

**Comment by asolkar** [comment]
As of release v1.0.1 (e49a6bd91eb1c41cd2dc00da61b222c4e1a7aab7), the add-on is marked Multi-Process compatible. Please file an issue if your run into problems
